package com.aiagent.ai_voice_agent.engine.tools

import android.content.Context
import android.util.Log
import com.aiagent.ai_voice_agent.engine.core.ToolRegistry
import com.aiagent.ai_voice_agent.engine.core.AgentMemory

/**
 * Регистрация всех инструментов в ToolRegistry.
 * Вынесено из EngineManager для уменьшения размера.
 */
object ToolRegistrar {
    private const val TAG = "ToolRegistrar"

    fun registerAll(toolRegistry: ToolRegistry, ctx: Context, memory: AgentMemory) {
        toolRegistry.register(GetCurrentTimeTool())
        toolRegistry.register(SystemControlTool(ctx))
        toolRegistry.register(OpenAppTool(ctx))
        toolRegistry.register(SelfAwarenessTool(ctx))
        toolRegistry.register(WebSearchTool(ctx))
        toolRegistry.register(SetAlarmTool(ctx))
        toolRegistry.register(CancelAlarmTool(ctx))
        toolRegistry.register(SetTimerTool(ctx))
        toolRegistry.register(CancelTimerTool(ctx))
        toolRegistry.register(GetLocationTool(ctx))
        toolRegistry.register(GetWeatherTool())
        toolRegistry.register(GetCurrencyRateTool())
        toolRegistry.register(ShareLocationTool(ctx))
        toolRegistry.register(MediaControlTool(ctx))
        toolRegistry.register(PlayStoreSearchTool())
        toolRegistry.register(OpenPlayStoreTool(ctx))
        toolRegistry.register(PlayYouTubeTool(ctx))
        toolRegistry.register(ConnectWifiTool(ctx))
        toolRegistry.register(CreateFileTool(ctx))
        toolRegistry.register(ReadFileTool(ctx))
        toolRegistry.register(ReadScreenTool())
        toolRegistry.register(ClickElementTool())
        toolRegistry.register(TypeTextTool())
        toolRegistry.register(NavigateTool())
        toolRegistry.register(ScrollTool())
        toolRegistry.register(ListClickableTool())
        toolRegistry.register(TakeScreenshotTool())
        toolRegistry.register(ExplainScreenTool())
        toolRegistry.register(ReadNotificationsTool(ctx))
        toolRegistry.register(DismissNotificationTool())
        toolRegistry.register(TakeSelfieTool(ctx))
        toolRegistry.register(TakePhotoTool(ctx))
        toolRegistry.register(CreateFolderTool(ctx))
        toolRegistry.register(ListFilesTool(ctx))
        toolRegistry.register(DeleteFileTool(ctx))
        toolRegistry.register(WriteFileTool(ctx))
        toolRegistry.register(OpenFileTool(ctx))
        toolRegistry.register(FileInfoTool(ctx))
        toolRegistry.register(BatteryInfoTool(ctx))
        toolRegistry.register(DeviceInfoTool(ctx))
        toolRegistry.register(StorageInfoTool(ctx))
        toolRegistry.register(ClipboardReadTool(ctx))
        toolRegistry.register(ClipboardWriteTool(ctx))
        toolRegistry.register(VolumeControlTool(ctx))
        toolRegistry.register(BrightnessControlTool(ctx))
        toolRegistry.register(FlashlightTool(ctx))
        toolRegistry.register(SendSmsTool(ctx))
        toolRegistry.register(MakeCallTool(ctx))
        toolRegistry.register(SearchContactsTool(ctx))
        toolRegistry.register(ReadSmsTool(ctx))
        toolRegistry.register(SearchSmsTool(ctx))
        toolRegistry.register(LaunchUrlTool(ctx))
        toolRegistry.register(ShareTextTool(ctx))
        toolRegistry.register(WriteToNotepadTool(ctx))
        toolRegistry.register(SendEmailTool(ctx))
        toolRegistry.register(ReplySmsTool(ctx))
        toolRegistry.register(ListAppsTool(ctx))
        toolRegistry.register(AppInfoTool(ctx))
        toolRegistry.register(NetworkInfoTool(ctx))
        toolRegistry.register(DrawImageTool(ctx))
        toolRegistry.register(BrowseWebsiteTool(ctx))
        toolRegistry.register(FindLinksTool(ctx))
        toolRegistry.register(SearchOnSiteTool(ctx))
        toolRegistry.register(DownloadFileTool(ctx))
        toolRegistry.register(SearchLocalMusicTool(ctx))
        toolRegistry.register(RememberFactTool(memory))
        toolRegistry.register(ForgetFactTool(memory))
        toolRegistry.register(ListMemoryTool(memory))
        toolRegistry.register(CreateEventTool(ctx))
        toolRegistry.register(ListEventsTool(ctx))
        toolRegistry.register(DeleteEventTool(ctx))
        toolRegistry.register(SetReminderTool(ctx))
        toolRegistry.register(OpenMapsTool(ctx))
        toolRegistry.register(BuildRouteTool(ctx))
        toolRegistry.register(FindNearbyTool(ctx))
        toolRegistry.register(RouteHomeTool(ctx))
        toolRegistry.register(RouteWorkTool(ctx))
        Log.d(TAG, "Tools registered (${toolRegistry.names.size}): ${toolRegistry.names}")
    }
}
